# Site settings
title: My Blog # 你的博客名字，可以定义修订
SEOTitle: 我的博客 | My Blog        #显示在浏览器上搜索的时候显示的标题
header-img: "img/zhihu.jpg"
tagline: "cn"
description: "这是我的博客"  # 一句话描述你的博客
baseurl: ""
url: "http://lizhiyuan.me"  # 此处填写你的博客地址

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "说点装逼的话。。。"
sidebar-avatar: /img/avatar-dog.jpg      # 个人头像

# About/contact
owner:
  name: "作者名字" # 填写作者信息：名字
  email: X@gmail.com # 填写作者信息：邮箱
  bio: "你的博客描述" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.ico # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.ico # 浏览器地址栏小图标，可自定义更改

# SNS settings
RSS: false
douban_username:    # 你的豆瓣id
twitter_username:   # 推特用户名
github_username:    # github用户名
facebook_username:  # facebook用户名
weibo_username:     # 微博用户名
zhihu_username:     # 知乎用户名

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "你的名字" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics:  # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "LiZhiyuan",
        href: "http://lizhiyuan.me/"
    },{
        title: "Hux Blog",
        href: "https://huangxuan.me/"
    }
]
